png("plot4.png",width=480,height=480)
par(mfrow=c(2,2))
plot(power1$time1,power1$Global_active_power,ylab="Global Active Power", xlab="",type="l")
plot(power1$time1,power1$Voltage,ylab="Voltage", xlab="datetime",type="l")
plot(power1$time1,power1$Sub_metering_1,type="l",ylab="Energy sub metering",xlab="")
lines(power1$time1,power1$Sub_metering_2,type="l",col="red")
lines(power1$time1,power1$Sub_metering_3,type="l",col="blue")
legend('topright', c("Sub_metering_1","Sub_metering_2","Sub_metering_3"), lty=1, col=c("black","red","blue"), bty='n', cex=.75)
plot(power1$time1,power1$Global_reactive_power,ylab="Global_reactive_power", xlab="datetime",type="l")
dev.off()
# the end