png("plot3.png",width=480,height=480)
plot(power1$time1,power1$Sub_metering_1,type="l",ylab="Energy sub metering",xlab="")
lines(power1$time1,power1$Sub_metering_2,type="l",col="red")
lines(power1$time1,power1$Sub_metering_3,type="l",col="blue")
legend('topright', c("Sub_metering_1","Sub_metering_2","Sub_metering_3"), lty=1, col=c("black","red","blue"), bty='y', cex=.75)
dev.off()